export const REMOVE_ERROR = 'REMOVE_ERROR'
export const REMOVE_LOADING = 'REMOVE_LOADING'
export const ADD_ERROR = 'ADD_ERROR'
export const ADD_LOADING = 'ADD_LOADING'

export const SET_SERVER_PRODUCTS = 'SET_SERVER_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_USER = 'SET_USER'
